"""
Falsification tests for the claims:
  C1: "FeatureFrame and PredictionFrame are near-1:1 twins"
  C3: "PredictionFrame moves verbatim AND the twins unify AND the sample-axis
       decision can be deferred"

Generated by /falsify on 2026-06-20, when both claims were FALSIFIED. The two
implementations being merged were not near-1:1 — they put the sample axis in
different places, and only one of them had feature names, metadata and a NaN check.
"Move it verbatim" was also impossible: the original imported pandas, which this
package forbids.

**All three were resolved by deciding rather than deferring.** ADR-012 fixed the
sample axis as the trailing axis, always explicit. ADR-011 rejected merging the
twins at all — they are separate sibling types that happen to share an index. And
the move was not verbatim: the identifier validation was rewritten numpy-only.

These originally asserted against the wording of the design document, because no
code existed yet. They now assert against the behaviour (2026-07-31, epic #208 /
S6 #214). One probe was retired rather than rewritten — see the note at the bottom.
"""

import numpy as np
import pytest

from views_frames import (
    FeatureFrame,
    FrameMetadata,
    PredictionFrame,
    SpatialLevel,
    SpatioTemporalIndex,
)


def test_falsify_tp_02_the_sample_axis_is_trailing_and_always_explicit():
    """🟥 Red team: the convention that had to be decided before anything else.

    Original probe: one type put the sample axis at position 1 of a 2-D array where
    it was always present; the other put it at position 2 of a 3-D array where it
    was optional. No single convention could host both, so deferring the decision
    while planning to unify was incoherent.

    ADR-012 settled it: the sample axis is always the **last** axis, and always
    present, even when there is only one sample. That is what makes the two shapes
    describable by one rule — (N, S) and (N, F, S) — rather than two special cases.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 1, 2], dtype=np.int64),
        unit=np.array([10, 11, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )

    # Many samples, and a single sample: the axis is present either way.
    many = PredictionFrame(np.ones((3, 5), dtype=np.float32), index)
    one = PredictionFrame(np.ones((3, 1), dtype=np.float32), index)
    assert many.values.shape == (3, 5) and many.sample_count == 5
    assert one.values.shape == (3, 1) and one.sample_count == 1
    assert one.is_sample is False, "S=1 is a real axis, not a sampled frame"

    # The feature frame puts it last too — after the feature axis, not before it.
    features = FeatureFrame(np.ones((3, 2, 4), dtype=np.float32), index, ["a", "b"])
    assert features.values.shape == (3, 2, 4)
    assert features.sample_count == 4, (
        "the sample axis must be last; reading 2 here means the feature axis was "
        "mistaken for it (ADR-012)"
    )

    # And it is never implicit: a 2-D feature array has to be lifted deliberately.
    lifted = FeatureFrame.from_2d(np.ones((3, 2), dtype=np.float32), index, ["a", "b"])
    assert lifted.values.shape == (3, 2, 1)


def test_falsify_tp_03_the_twins_were_not_unified_and_their_differences_are_real():
    """🟩 The parity claim, restated as what is actually true.

    Original probe: calling the two types "near-1:1" oversold the similarity and
    drove a plan to merge them. They differ on at least six axes.

    ADR-011 resolved it by **not merging them**. They are separate sibling types
    sharing only the index — so the differences do not need reconciling, they need
    stating. This checks both halves: no shared base class was introduced, and the
    differences the original probe listed are still genuinely there.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 2], dtype=np.int64),
        unit=np.array([10, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )

    # No shared base was ever introduced — they are siblings, not a hierarchy.
    shared = set(PredictionFrame.__mro__) & set(FeatureFrame.__mro__)
    assert shared == {object}, f"the frames acquired a shared base class: {shared}"

    # The differences are real, not cosmetic: one carries feature names, the other
    # has no such concept, and their arrays have different numbers of axes.
    features = FeatureFrame(
        np.ones((2, 3, 1), dtype=np.float32), index, ["a", "b", "c"]
    )
    predictions = PredictionFrame(np.ones((2, 4), dtype=np.float32), index)

    assert features.feature_names == ["a", "b", "c"]
    assert not hasattr(predictions, "feature_names")
    assert features.values.ndim == 3 and predictions.values.ndim == 2

    # Feature names are required and checked against the array — a constraint with
    # no counterpart on the prediction side.
    with pytest.raises(ValueError):
        FeatureFrame(np.ones((2, 3, 1), dtype=np.float32), index, ["only-one-name"])

    # What they genuinely do share is the index and the metadata header.
    assert predictions.index is index and features.index is index
    assert isinstance(predictions.metadata, FrameMetadata)
    assert isinstance(features.metadata, FrameMetadata)


# ---------------------------------------------------------------------------
# Retired probe
#
# `tp_01_prediction_frame_is_not_numpy_only_today` checked that the design document
# acknowledged a problem in the *original* implementation: it imported pandas and
# used `pd.isna` to validate identifiers, which this package forbids. The move was
# therefore not verbatim — the validation had to be rewritten numpy-only.
#
# That happened (register C-17), and the constraint is now enforced directly, and
# far more strongly than any prose check could manage:
#
#     tests/test_import_enforcement.py::test_package_dependency_dag
#
# which walks every module in the package and fails on any import of pandas, polars,
# geopandas, wandb, viewser or torch. Re-checking it here would duplicate that test
# without adding anything, so this probe is retired rather than rewritten.
# ---------------------------------------------------------------------------
