"""
Falsification test stubs for claim:
"views-frames can be a numpy-only, domain-free, maximally-stable leaf AND deliver
the cross-level cm<->pgm alignment its consumers require"

Generated by /falsify audit on 2026-06-20.

VERDICT: FALSIFIED (5 hard falsifications). The cross-level country<->grid join
that views-reporting and views-pipeline-core require is NOT derivable from the
(time, unit) integer arrays the leaf carries; it requires an external
priogrid_gid -> country_id mapping that is (a) domain reference data, (b) sourced
from viewser today, and (c) time-aware (country assignment varies by month). A
numpy-only, domain-free, maximally-stable leaf cannot deliver it; embedding the
mapping to deliver it violates the leaf's own no-domain-data (README sec 3, 11)
and maximal-stability (sec 8) constraints.

These tests are in TDD RED state -- they encode design-doc requirements that are
NOT yet met. They turn green only when the README resolves the cross-level
alignment / domain-data boundary decision (critique_00 finding #1).

The package has no code yet; these assert against the design documents.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_cl_01_crosslevel_mapping_home_is_decided():
    """
    Probe 1 (Category A/H): What does real cm<->pgm reconciliation depend on?

    Finding: views-reporting/reconciliation/reconciliation.py builds the join from
    build_country_to_grids_cache (metadata/entity_metadata.py), which derives
    priogrid_gid -> country_id from a viewser Queryset("pg_metadata",
    "priogrid_month") and even handles previous_country_id (time-varying border
    assignment). The mapping is external domain reference data, viewser-sourced,
    and NOT reconstructable from (time, unit) integer arrays.
    Severity: hard

    Expected: the README explicitly decides WHERE the country->cells mapping lives
    (leaf vs injected by consumer vs a separate reference package) and states that
    the leaf does not fetch or embed it.
    """
    # TODO: replace with a real check once the decision is documented.
    decided = re.search(
        r"(country[\s_-]*to[\s_-]*grid|cross-?level).*(inject|consumer-supplied|"
        r"reference package|not (embedded|owned) (by|in) the leaf)",
        README, re.I | re.S,
    )
    assert decided, (
        "README does not decide where the country->cells mapping lives; the "
        "cross-level join the consumers require needs external domain data the "
        "leaf forbids (see critique_00 #1)"
    )


def test_falsify_cl_02_crosslevel_not_expressible_in_declared_numpy_ops():
    """
    Probe 2 (Category C): Can pure numpy do one-to-many cross-level expansion?

    Finding: the declared sec 4.3 primitives (intersect, align/reindex,
    is_superset_of, argsort, searchsorted) are all same-axis set operations.
    country -> its cells is a one-to-many lookup against an external table; no
    same-axis set op can produce it from time[N]/unit[N]/level alone.
    Severity: hard

    Expected: the README either (a) adds a cross-level operation backed by an
    explicit (injected) mapping, or (b) explicitly scopes cross-level alignment
    OUT of the leaf and into consumer adapters.
    """
    # TODO: replace with a check of the actual index API once it exists.
    has_crosslevel_op = re.search(
        r"(to_grid|country_to_cells|cross[\s_-]*level (align|join|reindex|expand))",
        README, re.I,
    )
    assert has_crosslevel_op, (
        "No cross-level operation is specified; sec 4.3 lists only same-level "
        "set ops, which cannot express country->cells without an external mapping"
    )


def test_falsify_cl_03_no_internal_contradiction_on_alignment_ownership():
    """
    Probe 3 (Category B): sec 4.3 vs sec 3/11 self-consistency.

    Finding: sec 4.3 says alignment disagreements over (time, unit) "belong here,
    resolved once"; sec 3/11 forbid domain data and send the GAUL/country mapping
    to consumers. The cross-level join is an alignment operation whose data is
    forbidden -- the two sections contradict on exactly the consumer-required case.
    Severity: hard

    Expected: the README draws an explicit line between alignment LOGIC (in the
    leaf) and alignment DATA (out of the leaf), naming cross-level as data-bound.
    """
    # TODO: replace with a check for the explicit logic/data boundary statement.
    has_boundary = re.search(
        r"(alignment )?(logic|operation)s? (live|stay|belong).{0,80}"
        r"(data|mapping|reference).{0,80}(consumer|inject|outside|not in the leaf)",
        README, re.I | re.S,
    )
    assert has_boundary, (
        "README sec 4.3 (alignment belongs here) and sec 3/11 (no domain data) "
        "contradict on the cross-level case; no logic/data boundary is stated"
    )


def test_falsify_cl_04_stability_contract_survives_the_mapping():
    """
    Probe 4 (Category B): SAP / maximal-stability contract.

    Finding: the priogrid->country mapping is viewser-sourced reference data that
    versions (priogrid metadata revisions; time-varying country assignment).
    Embedding it in the leaf to satisfy the consumer requirement makes the leaf
    change for DATA reasons, violating sec 8 ("frequent MAJOR bumps => not stable
    enough; push volatility OUT to consumer adapters").
    Severity: hard

    Expected: the README states the country->cells mapping is NOT embedded in the
    leaf (so leaf stability is preserved), consistent with sec 8.
    """
    # TODO: replace once the decision is documented.
    mapping_excluded = re.search(
        r"(country[\s_-]*to[\s_-]*grid|gaul|priogrid.{0,20}country|country.{0,20}"
        r"priogrid).{0,120}(not (embedded|in the leaf)|stays? (in|with) (the )?"
        r"consumer|injected)",
        README, re.I | re.S,
    )
    assert mapping_excluded, (
        "If the versioned country->cells mapping is embedded to deliver "
        "cross-level alignment, the leaf changes for data reasons, breaking the "
        "sec 8 maximal-stability contract; README does not exclude it"
    )


def test_falsify_cl_05_crosslevel_is_specified_not_merely_motivated():
    """
    Probe 5 (Category H): Is cross-level alignment specified, or only motivated?

    Finding: cm<->pgm reconciliation appears in sec 4.3 PROSE as motivation ("what
    gives arrays the label-alignment that today drags pandas back in (cm<->pgm
    reconciliation ...)"), but the enumerated operation list is entirely
    same-level. Both consumers require cross-level alignment as a real operation
    (reporting perspective sec 8.2; pipeline-core perspective sec 9.3), yet it is
    nowhere specified with a home for its mapping.
    Severity: hard

    Expected: cross-level alignment appears as a specified operation/requirement
    in sec 4.3 or sec 13 (open decisions), not only as prose motivation.
    """
    in_open_decisions = "cross" in README.lower() and re.search(
        r"##\s*13[\s\S]*?(cross[\s_-]*level|country.{0,15}grid|cm.{0,5}pgm).{0,160}"
        r"(align|mapping|reconcil)",
        README, re.I,
    )
    assert in_open_decisions, (
        "Cross-level cm<->pgm alignment is required by both consumers but is only "
        "prose motivation in sec 4.3; it is not a specified operation nor an "
        "open decision in sec 13 (critique_00 #1, #5)"
    )
