"""
Falsification test stub for the claim:
  C4: "frames are immutable value objects (operations return new frames)"
      (README sec 3.3) preserves the scaling thesis (README sec 7) on the
      9-18 GB #181/C-186 tensors.

Generated by /falsify audit (pass 2) on 2026-06-20.

VERDICT: SOFT FALSIFICATION. Immutability is achievable, but the contract is
SILENT on copy-vs-view semantics -- the one thing that decides whether
"return a new frame" preserves sec 7's scaling guarantee or reintroduces the
multi-GB copy the package exists to kill.

Evidence:
  - pipeline-core PredictionFrame.collapse (prediction_frame.py:86-116) is
    memory-safe: it allocates a REDUCED (N,1) array and deep-copies only the small
    identifier arrays. Good.
  - PredictionFrame.load(mmap=True) (line 135-159) returns a read-only memmap and
    __init__ preserves the np.memmap subclass (line 35-41). Good.
  - BUT README sec 4 anticipates select()/with_metadata() and sec 3.3 says every
    operation 'returns new frames' -- with NO statement on whether a metadata-only
    or slice op COPIES or VIEWS the (multi-GB) `values` buffer. A naive
    new-frame-per-op that copies `values` reintroduces the exact object/copy blow-up
    sec 7 bans. Immutability (correctness, forbids C-184) and zero-copy (sec 7
    scaling) must be reconciled explicitly.

TDD RED: goes green when the README adds a copy-vs-view subsection (structural ops
share the buffer; mmap propagates) and the conformance suite pins it (a property:
with_metadata does not allocate a second `values` buffer).
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_im_01_copy_vs_view_semantics_are_specified():
    """Probe P4 (Category Performance/State): immutability vs the scaling thesis.

    The README must specify that structural/metadata-only operations return frames
    that SHARE the underlying values buffer (numpy view / zero-copy) and that mmap
    propagates -- otherwise sec 3.3 immutability silently violates sec 7 scaling on
    the #181-scale tensors.
    """
    specified = re.search(
        r"(copy|view|zero-?copy|share[sd]? the (underlying )?(array|buffer)|"
        r"mmap propagat|does not (allocate|copy) (the )?values)",
        README, re.I | re.S,
    )
    assert specified, (
        "README sec 3.3 mandates 'operations return new frames' but never specifies "
        "copy-vs-view semantics for `values`. On the 9-18 GB #181/C-186 tensors a "
        "naive new-frame-per-op copy reintroduces the blow-up sec 7 exists to kill. "
        "Add a copy/view contract and pin it in conformance."
    )
