"""
Falsification test for the claim:
  C4: "frames are immutable value objects (operations return new frames)" preserves
      the scaling guarantee on multi-gigabyte tensors

Generated by /falsify on 2026-06-20. The verdict was a SOFT falsification:
immutability was achievable, but nothing said whether returning a new frame *copies*
or *shares* the value buffer — and that is the whole question. On a 9–18 GB tensor,
a metadata-only operation that copies reintroduces exactly the memory blow-up this
package exists to prevent.

**Resolved by specifying both halves.** Structural operations share the buffer, so
immutability costs nothing at scale. The index is genuinely write-protected. The
value buffer is left writeable on purpose — that is what keeps sharing and memory
mapping possible — and mutating it in place is documented as unsupported (ADR-025).

This originally asserted against the wording of the design document. It now asserts
against the behaviour (2026-07-31, epic #208 / S6 #214).

**Overlap with the buffer-sharing tests elsewhere is deliberate.**
`tests/test_properties.py::test_with_metadata_shares_the_values_buffer` and
`tests/test_frame_parity.py::test_with_metadata_shares_buffer_parity` (the strongest form —
parametrised over all three frame types) pin the same sharing behaviour. This probe keeps it
because the *claim* it falsifies is about whether immutability is affordable at scale, not
about one method's contract. Kept on purpose (WET before DRY); `test_frame_parity.py` is
authoritative on the behaviour, this file on the claim.
"""

import numpy as np
import pytest

from views_frames import (
    FrameMetadata,
    PredictionFrame,
    SpatialLevel,
    SpatioTemporalIndex,
)


def test_falsify_im_01_structural_operations_share_the_buffer():
    """🟥 Red team: the answer that decides whether immutability is affordable.

    Original probe: "every operation returns a new frame" says nothing about whether
    the new frame carries a copy of the values. At the scale this package was built
    for, a copy per operation is the failure it was built to avoid.

    The resolution draws the line at whether an operation changes the *rows*:

      - **Metadata-only** operations share the buffer. This is the one that had to
        be zero-copy, because relabelling a 9 GB tensor must not duplicate it.
      - **Row selection** copies, and is documented as copying. It cannot do
        otherwise — picking arbitrary row positions out of an array is fancy
        indexing, and numpy always materialises the result. The cost is bounded by
        the size of the selection, not the size of the source.
      - **Reductions** allocate, which is correct: the output is genuinely new data.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 1, 2], dtype=np.int64),
        unit=np.array([10, 11, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )
    frame = PredictionFrame(np.arange(9, dtype=np.float32).reshape(3, 3), index)

    # Metadata-only: a new object, the same underlying memory.
    relabelled = frame.with_metadata(FrameMetadata(model="m"))
    assert relabelled is not frame
    assert np.shares_memory(relabelled.values, frame.values), (
        "with_metadata copied the value buffer — at multi-gigabyte scale this is "
        "the blow-up the package exists to prevent (ADR-025)"
    )

    # Row selection copies, as its docstring states. Pinned here so the documented
    # behaviour and the real behaviour cannot drift apart.
    subset = frame.select(np.array([0, 2]))
    assert not np.shares_memory(subset.values, frame.values)
    assert np.array_equal(subset.values, frame.values[[0, 2]])

    # A reduction is the case where allocating is correct — the output is genuinely
    # smaller, so there is nothing to share.
    from views_frames_summarize import collapse

    reduced = collapse(frame, np.mean)
    assert reduced.values.shape == (3, 1)
    assert not np.shares_memory(reduced.values, frame.values)


def test_falsify_im_02_the_index_is_enforced_read_only():
    """🟥 Red team: the half of immutability that is actually enforced.

    Sharing a buffer between frames is only safe if the shared parts cannot be
    changed underneath. The identifiers are enforced read-only in code; the value
    buffer is left writeable deliberately, so that sharing and memory mapping work
    at all, with in-place mutation documented as unsupported (ADR-025).

    This pins the enforced half, so a change that silently dropped the protection
    would be caught.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 2], dtype=np.int64),
        unit=np.array([10, 11], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )

    assert index.time.flags.writeable is False
    assert index.unit.flags.writeable is False

    with pytest.raises(ValueError):
        index.time[0] = 99

    # A frame does not weaken it: the index travels with its protection intact.
    frame = PredictionFrame(np.ones((2, 2), dtype=np.float32), index)
    assert frame.index.time.flags.writeable is False
