"""
Falsification test stubs for the claim:
  C5: "views-frames stays numpy-only and imports nothing internal" survives
      relocating SpatialLevel (README sec 4.3, sec 10.5) and adding MetricFrame
      (README sec 4.2).

Generated by /falsify audit (pass 2) on 2026-06-20.

VERDICT: MIXED.
  P5a SpatialLevel: SURVIVES the numpy-only test (it is stdlib `enum` only) --
      BUT relocating it verbatim ports two real defects into the leaf:
        1. C-65 reversed index tuple. domain/spatial.py:
             _INDEX_NAMES[PGM] = ("priogrid_gid", "month_id")   # entity-first
             _INDEX_NAMES[CM]  = ("country_id",  "month_id")    # entity-first
           All actual DataFrames are (month_id, entity) -- time-first. Relocating
           this ships a latent wrong-order contract in the leaf.
        2. Internal inconsistency: index_names uses `priogrid_gid` (pre-rename)
           while entity_column uses `priogrid_id` (post-rename) -- the same object
           disagrees with itself across the priogrid rename boundary.
      So SpatialLevel is numpy-safe but is NOT clean to relocate as-is.

  P5b MetricFrame: HARD FALSIFICATION of the single-frame abstraction. README sec 4
      defines a frame as "an array whose first axis is N rows, each carrying
      {time, unit}". MetricFrame (sec 4.2) is "(K, ...) keyed by (target, step,
      unit)" -- a different first-axis meaning and key space. It does not satisfy
      the frame definition the leaf is built on; hosting it either breaks sec 4 or
      makes the leaf a non-frame junk drawer. (views-evaluation already owns the
      eval-output vocabulary via EvaluationFrame -- README sec 4.2.)

TDD RED: green when the README (a) states SpatialLevel is relocated with the index
tuple order fixed and the gid/id inconsistency resolved, and (b) either justifies
MetricFrame as the same abstraction or relocates it out of the leaf.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_sl_01_spatiallevel_relocation_fixes_known_defects():
    """Probe P5a (Category Dependency): relocation ports C-65 + a gid/id mismatch.

    SpatialLevel is numpy-safe, but domain/spatial.py carries a reversed index
    tuple (entity-first vs the actual time-first order) and an internal
    priogrid_gid/priogrid_id inconsistency. The README must state the relocation
    FIXES these, not ports them.
    """
    fixes = re.search(
        r"(SpatialLevel|index_names).*(reversed|tuple order|time-?first|"
        r"month_id first|priogrid_gid.*priogrid_id|C-?65|fix)",
        README, re.I | re.S,
    )
    assert fixes, (
        "README relocates SpatialLevel (sec 4.3/10.5) but does not address its "
        "reversed index_names tuple (C-65) or its priogrid_gid/priogrid_id internal "
        "inconsistency (domain/spatial.py). Relocating as-is ships the bug into the leaf."
    )


def test_falsify_mf_01_metricframe_fits_the_frame_definition_or_is_excluded():
    """Probe P5b (Category Adequacy): MetricFrame breaks the frame definition.

    README sec 4: a frame = an array whose first axis is N rows carrying {time,unit}.
    MetricFrame (sec 4.2) is (K, ...) keyed by (target, step, unit). Either the
    README justifies it as the same abstraction or excludes it from the leaf.
    """
    resolved = re.search(
        r"MetricFrame.*(does not fit|different (shape|abstraction)|stays in|"
        r"belongs (in|to)|excluded|out of (the )?leaf|views-evaluation owns)",
        README, re.I | re.S,
    )
    assert resolved, (
        "README places MetricFrame (sec 4.2) in the leaf but it is keyed by "
        "(target, step, unit), not (N rows of {time, unit}) -- it does not satisfy "
        "the sec 4 frame definition. Justify it as the same abstraction or exclude it."
    )
