"""
Falsification test stubs for the claims:
  C1: "FeatureFrame and PredictionFrame are near-1:1 twins" (README sec 1, sec 4.1)
  C3: "PredictionFrame moves verbatim AND the twins unify AND the sample-axis
       decision can be deferred" (README sec 10.2 vs sec 4.1 vs sec 13.6)

Generated by /falsify audit (pass 2) on 2026-06-20. Companion to
test_falsification_domain_free_crosslevel.py (pass 1, claim C2).

VERDICT: FALSIFIED (hard). The two real implementations are NOT near-1:1, and
"move PredictionFrame verbatim" is mutually exclusive with "numpy-only leaf"
and with "unify the twins / defer the sample-axis decision". Evidence:

  views-pipeline-core/views_pipeline_core/data/prediction_frame.py
    - line 5:  `import pandas as pd`   <-- the core type imports pandas
    - line 68: `np.any(pd.isna(arr))`  <-- pandas used to validate identifiers
    - y_pred shape (N, S): sample axis is axis 1, ALWAYS present (S>=1)
    - has: collapse(), load(mmap=...), pandas NaN-check; save = npy + npz
  views-datafactory/src/datafactory_adapters/feature_frame.py
    - numpy + json only (no pandas)
    - y_features shape (N, D) or (N, D, S): sample axis is axis 2, OPTIONAL
    - has: feature_names (required), metadata, from_grid(), is_sample, n_features
    - NO NaN-check on identifiers; save = npy + npz + feature_names.json + metadata.json

Consequences (each a hard falsification of the as-stated design):
  - "verbatim move" of PredictionFrame into a numpy-only leaf (README sec 3.1)
    is impossible: it would import pandas into the core, which sec 3.1 forbids.
    Therefore the move is NOT verbatim -- the NaN-check must be rewritten numpy-only.
  - "unify the twins" cannot coexist with "defer the sample-axis decision"
    (README sec 13.6): the sample axis is at a DIFFERENT position in each twin,
    so a single type cannot host both without first deciding the convention.
  - "near-1:1" oversells the parity: the twins differ on sample-axis position,
    feature_names/metadata, NaN validation, collapse, mmap, and save footprint.

TDD RED: these assert against the design docs; they go green only when the README
resolves (a) the numpy-only rewrite of PredictionFrame's validation, (b) the
sample-axis convention BEFORE unification, and (c) a precise twin-parity statement.
The package has no code yet.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
README = (REPO / "README.md").read_text(encoding="utf-8")


def test_falsify_tp_01_prediction_frame_is_not_numpy_only_today():
    """Probe P1/P3 (Category Contract): the 'verbatim move' claim.

    Finding (hard): pipeline-core PredictionFrame imports pandas (line 5) and uses
    pd.isna for identifier validation (line 68). README sec 10.2 says 'move
    PredictionFrame here verbatim'; README sec 3.1 says the core must NEVER import
    pandas. Both cannot hold. The README must acknowledge the validation rewrite
    (verbatim is false) before the move can be called verbatim.
    """
    acknowledges = re.search(
        r"(verbatim).*(rewrite|re-?implement|numpy[- ]only validation|drop(ping)? pandas|"
        r"pd\.isna|NaN check)|"
        r"(PredictionFrame).*(import|use)s? pandas",
        README, re.I | re.S,
    )
    assert acknowledges, (
        "README claims a verbatim move of PredictionFrame but does not acknowledge "
        "that PredictionFrame imports pandas (pd.isna, prediction_frame.py:5,68) and "
        "must be rewritten numpy-only to satisfy sec 3.1 -- so the move is NOT verbatim."
    )


def test_falsify_tp_02_sample_axis_decided_before_unification():
    """Probe P3 (Category Logic): unify + defer sample-axis is inconsistent.

    Finding (hard): PredictionFrame's sample axis is axis 1 of a 2D (N,S) array
    (always present); FeatureFrame's is axis 2 of a 3D (N,D,S) array (absent when
    2D). A unified type cannot carry both conventions. README sec 13.6 lists the
    sample-axis convention as an OPEN decision while sec 4.1/sec 10 already plan to
    unify -- the decision must be CLOSED before unification, not deferred.
    """
    # The README must state the sample-axis convention as decided (not merely list
    # it as open) for unification to be coherent.
    open_decision = re.search(r"#{0,3}\s*13\.6|sample-?axis convention.*\?", README, re.I | re.S)
    decided = re.search(
        r"sample[- ]axis.*(is|shall be|convention:|decided|S=1 is (an explicit|absent))",
        README, re.I | re.S,
    )
    assert decided and not open_decision, (
        "README unifies the twins (sec 4.1/10) while the sample-axis convention is "
        "still an OPEN decision (sec 13.6). PF (axis 1, always) and FF (axis 2, "
        "optional) cannot share one type until this is closed."
    )


def test_falsify_tp_03_twin_parity_is_stated_precisely_not_as_near_1to1():
    """Probe P1 (Category Contract): 'near-1:1' is imprecise and misleading.

    Finding: the twins diverge on at least six axes (sample-axis position,
    feature_names, metadata, identifier NaN-validation, collapse/mmap, save
    footprint). The README should state the EXACT shared surface and the EXACT
    deltas, not assert 'near-1:1', which drives the over-optimistic verbatim/unify plan.
    """
    precise = re.search(
        r"(FeatureFrame).*(adds|extra|differs).*(feature_names|metadata).*"
        r"(sample[- ]axis|NaN|validation|save)",
        README, re.I | re.S,
    )
    assert precise, (
        "README characterises the twins as 'near-1:1' but does not enumerate the "
        "real deltas (sample-axis position, feature_names/metadata, NaN validation, "
        "collapse/mmap, save sidecars). State the shared surface and deltas precisely."
    )
