"""
Falsification tests for the claim:
  C5: "views-frames stays numpy-only and imports nothing internal" survives
      relocating SpatialLevel and adding MetricFrame

Generated by /falsify on 2026-06-20. The verdict was MIXED:

  SpatialLevel was safe to move (standard library only), but moving it *as-is*
  would have carried two real defects along: an index tuple in entity-first order
  when every actual table is time-first, and an object that disagreed with itself
  about the priogrid identifier's name — `priogrid_gid` in one place, `priogrid_id`
  in another, straddling a rename.

  MetricFrame was a hard falsification. A frame here is an array whose first axis is
  N rows, each carrying a (time, unit) pair. MetricFrame is keyed by (target, step,
  unit) — a different first axis and a different key space. Hosting it would have
  either broken that definition or turned this package into a junk drawer.

**Both were resolved by deciding.** ADR-015 moved SpatialLevel with the tuple order
corrected and one consistent spelling — fix, do not port. ADR-020 put MetricFrame in
views-evaluation, where the evaluation vocabulary already lives.

These originally asserted against the wording of the design document. They now
assert against the behaviour (2026-07-31, epic #208 / S6 #214).
"""

import pathlib

import pytest

import views_frames
from views_frames import SpatialLevel, spatial_level

# The spelling ADR-015 removed. It must not come back — see below for why this
# particular guard is not hypothetical.
LEGACY_SPELLING = "priogrid_gid"


def test_falsify_sl_01_the_legacy_identifier_spelling_never_comes_back():
    """🟥 Red team: a guard against something that has already been attempted.

    Original probe: moving SpatialLevel as-is would have carried a `priogrid_gid` /
    `priogrid_id` inconsistency into this package. ADR-015's answer was to fix it
    during the move, so one spelling — `priogrid_id` — is used everywhere.

    **This is not a hypothetical guard.** On 2026-07-27 a branch appeared adding
    exactly what ADR-015 removed: an alias table mapping `priogrid_gid` to
    `priogrid_id`, plus a helper to normalise between them. It was discarded, but it
    was written — the pressure to reintroduce the old spelling is real, and comes
    from consumers still using it upstream.

    The right place to rename is upstream, before data reaches this package. This
    package carries one vocabulary and does not translate between spellings.
    """
    for level in SpatialLevel:
        assert LEGACY_SPELLING not in level.entity_column
        assert not any(LEGACY_SPELLING in name for name in level.index_names)

    # Read the module's source rather than inspecting its objects. An earlier
    # version of this test walked `dir(module)` looking for a dict whose contents
    # held the old spelling, plus an attribute named like a normaliser. That was
    # too specific to the shape of the one attempt we had seen: a code review
    # showed it could be walked around by a `frozenset`, a tuple of pairs, a
    # constant nested in a class, or simply a function named
    # `priogrid_gid_to_id` — which passed while being exactly the thing banned.
    #
    # The spelling has no legitimate use anywhere in this module, so its absence
    # from the source is the honest check, and there is nothing to evade.
    # Comments are excluded so this file's own explanation, and any future
    # comment saying why the spelling is banned, do not trip it.
    source = pathlib.Path(spatial_level.__file__).read_text(encoding="utf-8")
    code = "\n".join(
        line for line in source.splitlines() if not line.strip().startswith("#")
    )
    assert LEGACY_SPELLING not in code, (
        f"{LEGACY_SPELLING} appears in spatial_level.py outside a comment — this "
        "package carries one vocabulary (ADR-015) and renames happen upstream, "
        "before data reaches it"
    )


def test_falsify_sl_01b_the_index_tuple_is_time_first():
    """🟥 Red team: the reversed tuple that would have shipped a silent wrong order.

    Original probe: the version being moved listed its index as (entity, time) while
    every actual table is (time, entity). Moving it unchanged would have put a
    latent wrong-order contract into the package every other repository depends on —
    the kind of defect that yields plausible wrong answers rather than an error.
    """
    for level in SpatialLevel:
        assert level.index_names[0] == "month_id", (
            f"{level.name} lists {level.index_names} — the time column must come "
            "first (ADR-015). An entity-first tuple is the reversed order that was "
            "fixed during the move, not ported."
        )
        assert level.index_names[1] == level.entity_column


def test_falsify_mf_01_metricframe_is_not_defined_here():
    """🟩 The boundary that keeps the frame definition meaningful.

    Original probe: a frame here is an array whose first axis is N rows carrying a
    (time, unit) pair. MetricFrame is keyed by (target, step, unit) instead, so it
    does not fit — and hosting it anyway would have made "frame" mean nothing.

    ADR-020 put it in views-evaluation. What this package offers instead is the
    shared envelope check, so a type defined elsewhere can still be validated
    against the same rules.
    """
    assert not hasattr(views_frames, "MetricFrame")
    assert "MetricFrame" not in views_frames.__all__

    # Every frame this package does define is keyed the same way, which is what
    # makes the definition worth having.
    for name in ("PredictionFrame", "FeatureFrame", "TargetFrame"):
        assert name in views_frames.__all__

    # The seam is deliberate: the envelope check is published precisely for types
    # that are not defined here.
    from views_frames.conformance import assert_frame_envelope

    assert callable(assert_frame_envelope)


def test_falsify_sl_02_the_vocabulary_stays_labels_only():
    """🟥 Red team: SpatialLevel must stay a label, not become a geography.

    The reason this type was safe to move at all is that it holds names, not data.
    If it ever gained a cell list, a boundary, or a lookup table, it would drag
    domain data into a package that forbids it — the same failure the cross-level
    tests guard from the other direction.
    """
    for level in SpatialLevel:
        assert isinstance(level.entity_column, str)
        assert isinstance(level.index_names, tuple)
        assert all(isinstance(name, str) for name in level.index_names)

    with pytest.raises(ValueError):
        SpatialLevel("not-a-level")
