"""
Falsification tests for the claim:
"views-frames can be a numpy-only, domain-free, maximally-stable leaf AND deliver
the cross-level cm<->pgm alignment its consumers require"

Originally generated by /falsify on 2026-06-20, when the claim was FALSIFIED: the
country<->grid join that views-reporting and views-pipeline-core need is not
derivable from the (time, unit) integer arrays this package carries. It needs an
external priogrid_gid -> country_id mapping that is domain reference data,
externally sourced, and time-varying (a cell's country assignment changes by month).

**ADR-014 resolved it by splitting the operation from the data.** This package owns
the remapping *operation*; the caller supplies the *mapping*, and the package never
embeds or fetches one. That is what keeps it numpy-only and domain-free while still
delivering the alignment consumers need.

These tests were written before any code existed, so they originally asserted
against the wording of the design document. The code has existed since v0.1.0, so
they now assert against the behaviour instead (2026-07-31, epic #208 / S5 #213). Each one
fails if the resolution stops holding — which is what a falsification test is for.
"""

import numpy as np
import pytest

from views_frames import SpatialLevel, SpatioTemporalIndex


def test_falsify_cl_01_crosslevel_mapping_must_be_injected():
    """🟥 Red team: the package must refuse to guess the mapping.

    Original probe: does anything decide *where* the country->cells mapping lives?
    ADR-014's answer is that the caller supplies it. If a future change ever made
    the package fall back to a built-in mapping, the domain-free guarantee would be
    gone — so asking for a cross-level remap without a mapping must fail loudly,
    never silently produce an answer.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 1, 2], dtype=np.int64),
        unit=np.array([10, 11, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )

    with pytest.raises(ValueError, match="requires an injected"):
        index.cross_level_align({}, SpatialLevel("cm"))

    # A mapping that does not cover every row is also a refusal, not a guess.
    with pytest.raises(ValueError):
        index.cross_level_align({(1, 10): 100}, SpatialLevel("cm"))


def test_falsify_cl_02_crosslevel_expansion_works_when_the_mapping_is_supplied():
    """🟩 The operation the same-level primitives could not express.

    Original probe: the declared primitives (intersect, reindex, is_superset_of,
    searchsorted) are all same-axis set operations, and none of them can turn a grid
    cell into the country that contains it. That is still true — which is why this
    is a separate operation that takes the mapping as an argument.

    The mapping is keyed by (time, unit), not unit alone, because a cell's country
    assignment changes over time. Cells 10 and 11 both sit in country 100 at time 1;
    cell 10 has moved to country 200 by time 2.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 1, 2], dtype=np.int64),
        unit=np.array([10, 11, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )
    mapping = {(1, 10): 100, (1, 11): 100, (2, 10): 200}

    country = index.cross_level_align(mapping, SpatialLevel("cm"))

    assert country.level == SpatialLevel("cm")
    assert np.array_equal(country.unit, np.array([100, 100, 200]))
    # Time is preserved: remapping changes the spatial axis only.
    assert np.array_equal(country.time, index.time)


def test_falsify_cl_03_the_operation_lives_here_and_the_data_does_not():
    """🟥 Red team: the logic/data boundary that resolved the contradiction.

    Original probe: "alignment belongs here, resolved once" contradicted "no domain
    data in this package" on exactly the cross-level case. ADR-014 drew the line
    between alignment *logic* (here) and alignment *data* (supplied by the caller).

    This checks the boundary from both sides: the operation is present, and no
    mapping is stored anywhere in the package for it to fall back on.
    """
    index = SpatioTemporalIndex(
        time=np.array([1], dtype=np.int64),
        unit=np.array([10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )

    # The logic side: the operation exists, on the index, taking a mapping argument.
    assert callable(index.cross_level_align)
    assert callable(index.cross_level_align_arrays)

    # The data side: nothing the index holds is a mapping table. Its entire state is
    # the two identifier arrays plus a level label.
    held = dict(vars(index))
    assert set(held) == {"_time", "_unit", "_level"}, (
        f"the index gained state beyond its identifiers and level: {sorted(held)}"
    )
    assert isinstance(held["_time"], np.ndarray)
    assert isinstance(held["_unit"], np.ndarray)
    assert isinstance(held["_level"], SpatialLevel)


def test_falsify_cl_04_the_mapping_is_never_stored_on_the_result():
    """🟥 Red team: the stability contract that embedding would break.

    Original probe: the priogrid->country mapping is externally-sourced reference
    data that versions, and a cell's country assignment changes over time. If this
    package held that mapping, it would have to change for *data* reasons — which is
    what "maximally stable" forbids, since every repository in the platform depends
    on this one.

    So a remapped index must keep no reference to the mapping it was produced with.
    Supplying a mapping is a one-off argument, not a stored dependency.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 2], dtype=np.int64),
        unit=np.array([10, 10], dtype=np.int32),
        level=SpatialLevel("pgm"),
    )
    mapping = {(1, 10): 100, (2, 10): 200}

    country = index.cross_level_align(mapping, SpatialLevel("cm"))

    assert set(vars(country)) == {"_time", "_unit", "_level"}

    # Mutating the caller's mapping afterwards cannot change an existing result —
    # the values were read, not retained.
    before = country.unit.copy()
    mapping[(1, 10)] = 999
    assert np.array_equal(country.unit, before)


def test_falsify_cl_05_the_time_varying_key_is_real_not_decorative():
    """🟥 Red team: keying on (time, unit) has to actually matter.

    Original probe: cross-level alignment appeared only as prose motivation, never
    as a specified operation. It is now specified and implemented — and this checks
    the part that is easy to get wrong.

    A mapping keyed by unit alone would be simpler and would pass every other test
    here. It would also be wrong: borders move, so the same cell belongs to
    different countries at different times. The same unit must be able to produce
    two different answers.
    """
    index = SpatioTemporalIndex(
        time=np.array([1, 2], dtype=np.int64),
        unit=np.array([10, 10], dtype=np.int32),  # one cell, two months
        level=SpatialLevel("pgm"),
    )

    country = index.cross_level_align({(1, 10): 100, (2, 10): 200}, SpatialLevel("cm"))

    assert np.array_equal(country.unit, np.array([100, 200])), (
        "the same unit at two times produced the same country — the mapping is "
        "being keyed by unit alone, which cannot express a moving border (ADR-014)"
    )
