"""Tower-figure generators — the PRN06 overlay + detail plots (v2, tower upright).

Provenance: the figures of FAO Project 02 Pre-Release Note 06 (`tower_overlay.pdf`,
`tower_detail.pdf`, 2026-06-24) were generated by ephemeral scratchpad scripts,
recovered verbatim from a session transcript on 2026-07-24, and made permanent here
(see `research/figures/NOTE.md`).

v2 (2026-07-24) corrects the as-published rendering, values unchanged: the original
drew credible level ascending, putting the WIDE floors at the top — an upside-down
tower whose "tip" marker sat mid-structure (a *tower-middle* MAP, visually). v2
inverts the vertical arrangement so the tower stands upright: 99% base at the bottom,
floors narrowing upward, the ``tip_mass`` (50%) floor as the top of the published
tower with the MAP marker at its tip, and the sub-50% floors as a faint spire
converging on the MAP above it. Also fixed: twin-axis label collisions between
panels, the endpoint "curtain" verticals, and the detail figure's annotation
collision.

The tips/towers come from the installed `views_frames_summarize` public API —
`tower_point` (median of the ``tip_mass`` floor — 0.25, the top floor of the
published tower, since ADR-019 Amendment 3), `hdi_tower`
(outside-in nested floors on the canonical grid), `bimodality`. Seeds are fixed
(overlay: 7, detail: 3), so reruns reproduce the published values exactly:
see NOTE.md for the current expected tip values (tip_mass = 0.25, ADR-019 Am. 3).

Run (matplotlib rides the [docs] extra; never a package dependency):

    uv run --extra docs python research/figures/make_tower_figs.py
    uv run --extra docs python research/figures/make_tower_figs.py \
        --figdir path/ --which overlay

Outputs default to ``reports/plots/`` (gitignored — generated artifacts stay out of
git; a deliverable's copy travels with the deliverable). Plotting deliberately lives
under ``research/``, NOT ``src/``: the frames wheel is numpy-only and its charters
exclude plotting six times over (ADR-017, ADR-023, Summarize/Reconcile CIC §2). If
cross-repo demand for these plots ever materializes, they graduate to a separate
unfrozen distribution or views-reporting — never into this wheel.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt

import views_frames as vf
import views_frames_summarize as vfs
from views_frames_summarize import config

FLOORS = np.asarray(config.canonical_floors())
PUBLISHED = {0.25: "#c0392b", 0.5: "#2e86c1", 0.9: "#7d3c98", 0.95: "#117a65",
             0.99: "#1f4e79"}
TOWER_C = "#1f4e79"  # deep blue (faint internal floors)
TIP_C = "#c0392b"  # red


def _index(n: int) -> vf.SpatioTemporalIndex:
    return vf.SpatioTemporalIndex(
        time=np.arange(n, dtype=np.int64),
        unit=np.arange(100, 100 + n, dtype=np.int32),
        level=vf.SpatialLevel.PGM,
    )


def _frame(draws: np.ndarray) -> vf.PredictionFrame:
    return vf.PredictionFrame(np.asarray(draws, np.float32)[None, :], _index(1))


def _tower_and_tip(draws: np.ndarray) -> tuple[np.ndarray, float, float]:
    f = _frame(draws)
    tower = vfs.hdi_tower(f, masses=tuple(float(m) for m in FLOORS))[0]  # (F, 2)
    tip = float(vfs.tower_point(f).values.reshape(-1)[0])
    flag = float(vfs.bimodality(f).reshape(-1)[0])
    return tower, tip, flag


def _draw_upright_tower(ax2, tower: np.ndarray, tip: float, *, label_bands: bool):
    """Draw the published tower standing upright on an inverted credible-mass axis.

    The axis is inverted so mass DECREASES upward: the 99% base sits at the bottom
    and the tower narrows upward, ending at the ``tip_mass`` (50%) floor — the TOP
    floor of the published tower. The tip marker sits on that top floor: the
    tower-tip MAP is the median of the top HDI, exactly as the name promises.
    Floors below ``tip_mass`` (the canonical grid's fine machinery) are NOT drawn —
    rendering them as a spire above the 50% floor would un-top the tower and make
    the tip read as mid-structure (the v2 mistake).
    """
    tip_mass = float(config.get("tip_mass"))
    ax2.set_ylim(tip_mass - 0.06, 1.03)
    ax2.invert_yaxis()  # mass 1.0 at the bottom (base), tip_mass at the top (tip)
    for m, (lo, hi) in zip(FLOORS, tower, strict=True):
        if m < tip_mass - 1e-9:
            continue  # internal grid below the tip floor: machinery, not the tower
        if any(np.isclose(m, pm) for pm in PUBLISHED):
            c = PUBLISHED[min(PUBLISHED, key=lambda pm: abs(pm - m))]
            if hi - lo <= 1e-9:
                # a degenerate band (e.g. the tip floor collapsed onto the zero atom
                # of a zero-inflated cell): zero width renders invisibly — and the
                # tip dot sits at the same point, hiding any filled marker. Draw an
                # OPEN diamond around the spot so the collapsed band stays legible.
                ax2.plot([lo], [m], marker="D", ms=11, zorder=8,
                         markerfacecolor="none", markeredgecolor=c,
                         markeredgewidth=1.4)
            else:
                ax2.plot([lo, hi], [m, m], color=c, lw=3.0, solid_capstyle="round",
                         zorder=5)
            if label_bands:
                ax2.text(hi, m, f"  {int(round(m * 100))}%", va="center", ha="left",
                         fontsize=7.5, color=c, fontweight="bold")
        else:
            ax2.plot([lo, hi], [m, m], color=TOWER_C, lw=1.1, alpha=0.35,
                     solid_capstyle="round", zorder=3)
    # the tip: marker ON TOP of the published tower (the tip_mass floor)
    ax2.axvline(tip, color=TIP_C, lw=1.6, ls="--", zorder=6)
    ax2.plot([tip], [tip_mass], marker="o", color=TIP_C, ms=7, zorder=7,
             markeredgecolor="white", markeredgewidth=0.8)


def overlay_cases(n: int = 2000, seed: int = 7) -> list[tuple[str, np.ndarray]]:
    """The four-shape zoo of the PRN06 overlay (seed 7 reproduces the note)."""
    rng = np.random.default_rng(seed)
    n_zero = int(0.45 * n)
    return [
        ("Right-skewed unimodal", rng.lognormal(0.5, 0.55, n)),
        ("Near-symmetric unimodal", rng.normal(6.0, 1.2, n)),
        (
            "Zero-inflated + positive body",
            np.concatenate([np.zeros(n_zero), rng.lognormal(0.7, 0.5, n - n_zero)]),
        ),
        (
            "Bimodal (assumption violated)",
            np.concatenate(
                [rng.normal(2.0, 0.6, n // 2), rng.normal(9.0, 0.8, n - n // 2)]
            ),
        ),
    ]


def make_overlay(figdir: Path, n: int = 2000, seed: int = 7) -> None:
    """The 2x2 upright-tower-over-histogram overlay across the four-shape zoo."""
    cases = overlay_cases(n, seed)
    fig, axes = plt.subplots(2, 2, figsize=(11.5, 8.4), layout="constrained")

    for k, (ax, (title, draws)) in enumerate(zip(axes.ravel(), cases, strict=True)):
        draws = np.asarray(draws, np.float32)
        tower, tip, flag = _tower_and_tip(draws)

        ax.hist(
            draws, bins=60, density=True, color="#e3e6ea", edgecolor="#c8cdd4",
            linewidth=0.3, zorder=1,
        )
        ax.set_xlabel("forecast value")
        ax.set_title(title, fontsize=11, fontweight="bold")
        ax.tick_params(axis="y", labelcolor="#777")
        if k % 2 == 0:  # outer-left panels only — no mid-figure label collisions
            ax.set_ylabel("empirical density", color="#777")

        ax2 = ax.twinx()
        _draw_upright_tower(ax2, tower, tip, label_bands=(k == 0))
        ax2.tick_params(axis="y", labelcolor=TOWER_C)
        if k % 2 == 1:  # outer-right panels only
            ax2.set_ylabel("credible mass  (99% base ↓ → 25% tip ↑)",
                           color=TOWER_C)

        tag = f"MAP (tip) = {tip:.2f}" + ("   [bimodal flag]" if flag >= 0.5 else "")
        ax2.text(
            0.98, 0.97, tag, transform=ax.transAxes, ha="right", va="top",
            fontsize=8.5, color=TIP_C,
            bbox={"boxstyle": "round,pad=0.25", "fc": "white", "ec": TIP_C,
                  "alpha": 0.9},
        )

    fig.suptitle(
        f"The HDI tower over the empirical forecast distribution (synthetic, $n={n}$)",
        fontsize=12.5, fontweight="bold",
    )
    fig.savefig(figdir / "tower_overlay.pdf")
    fig.savefig(figdir / "tower_overlay.png", dpi=150)
    plt.close(fig)
    tips = [round(_tower_and_tip(np.asarray(c[1], np.float32))[1], 2) for c in cases]
    print("wrote tower_overlay.pdf/.png; tips:", tips)


def make_detail(figdir: Path, n: int = 2000, seed: int = 3) -> None:
    """One right-skewed posterior with the upright tower + published bands labeled."""
    rng = np.random.default_rng(seed)
    draws = rng.lognormal(0.6, 0.5, n).astype(np.float32)
    tower, tip, _ = _tower_and_tip(draws)

    fig, ax = plt.subplots(figsize=(8.6, 4.8), layout="constrained")
    ax.hist(draws, bins=70, density=True, color="#e3e6ea", edgecolor="#c8cdd4",
            lw=0.3)
    ax.set_xlabel("forecast value")
    ax.set_ylabel("empirical density", color="#777")
    ax.tick_params(axis="y", labelcolor="#777")

    ax2 = ax.twinx()
    _draw_upright_tower(ax2, tower, tip, label_bands=True)
    ax2.set_ylabel("credible mass  (99% base ↓ → 25% tip ↑)", color=TOWER_C)
    ax2.tick_params(axis="y", labelcolor=TOWER_C)
    # annotation in the clear space beside the spire, not across the floors
    tip_mass = float(config.get("tip_mass"))
    ax2.annotate(
        f"MAP (tip) = {tip:.2f}", xy=(tip, tip_mass), xytext=(0.97, 0.72),
        textcoords=ax.transAxes, ha="right", va="center", fontsize=9.5,
        color=TIP_C, fontweight="bold",
        arrowprops={"arrowstyle": "->", "color": TIP_C, "lw": 1.0,
                    "shrinkA": 4, "shrinkB": 6},
    )
    ax.set_title(
        "Nested HDI tower and tower-tip MAP on one empirical posterior (synthetic)",
        fontsize=11, fontweight="bold",
    )
    fig.savefig(figdir / "tower_detail.pdf")
    fig.savefig(figdir / "tower_detail.png", dpi=150)
    plt.close(fig)
    print("wrote tower_detail.pdf/.png; tip", round(tip, 2))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--figdir", type=Path, default=Path("reports/plots"),
        help="output directory (default: reports/plots — gitignored)",
    )
    parser.add_argument(
        "--which", choices=("overlay", "detail", "all"), default="all",
    )
    args = parser.parse_args()
    args.figdir.mkdir(parents=True, exist_ok=True)
    if args.which in ("overlay", "all"):
        make_overlay(args.figdir)
    if args.which in ("detail", "all"):
        make_detail(args.figdir)


if __name__ == "__main__":
    main()
